### ISSUE TITLE
Include pip install in script

### ISSUE THREAD

**Issue by roadelou** [theodumont/bash-sgd#1]
The `pip install -r requirements.txt` is not part of the bash code, why is that so?

This is a bit surprising given that the bash code does test whether python is installed on the system. Since you are being that cautious in the shell file, you might as well install the python modules yourself with `python3 -m pip install -r requirements.txt`.

**Comment by theodumont** [comment]
I chose to put the `pip install` outside the `.sh` script because I didn't want to hide the install of the packages through `pip` inside the script, to avoid surprising the user with packages installs in case he/she wants to use a virtual environment. But actually putting the `pip install` in the script and simply recommending the user to use a virtual environment in the `README` might be more convenient.
